# Generated by Django 6.0.5 on 2026-05-16 09:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_vault', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='')),
                ('body', wagtail.fields.StreamField([('image', 4), ('gallery', 6), ('video', 9), ('video_gallery', 11), ('audio', 13), ('text', 14), ('heading', 15), ('raw_html', 16)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Photo credit', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('keep', 'Keep'), ('delete', 'Delete'), ('undecided', 'Undecided')]}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('credit', 2), ('keep', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 1), ('items', 5)]], {}), 7: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('video', 7), ('caption', 1), ('autoplay', 8), ('loop', 8), ('keep', 3)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 1), ('items', 10)]], {}), 12: ('wagtailmedia.blocks.AudioChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('audio', 12), ('caption', 1), ('keep', 3)]], {}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 15: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'max_length': 200}), 16: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML'})})),
            ],
            options={
                'verbose_name': 'Media Gallery Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PhotoReviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('source_filter', models.CharField(choices=[('all', 'All sources'), ('drive', 'Drive only'), ('gmail', 'Gmail only')], default='all', max_length=20)),
                ('body', wagtail.fields.StreamField([('gallery', 6), ('image', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Photo credit', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('keep', 'Keep'), ('delete', 'Delete'), ('undecided', 'Undecided')]}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 0), ('credit', 2), ('keep', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 5)]], {})})),
            ],
            options={
                'verbose_name': 'Photo Review Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VaultHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='Your Google media, organized.', max_length=200)),
            ],
            options={
                'verbose_name': 'Vault Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoReviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('video_gallery', 6), ('video', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 1: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('keep', 'Keep'), ('delete', 'Delete'), ('undecided', 'Undecided')]}), 4: ('wagtail.blocks.StructBlock', [[('video', 1), ('caption', 0), ('autoplay', 2), ('loop', 2), ('keep', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 5)]], {})})),
            ],
            options={
                'verbose_name': 'Video Review Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
