# Generated by Django 6.0.5 on 2026-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_vault', '0002_mediagallerypage_photoreviewpage_vaulthomepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultimage',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vaultmedia',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
