# Generated by Django 6.0.5 on 2026-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_vault', '0002_mediagallerypage_photoreviewpage_vaulthomepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField(help_text='Absolute path to the stripped file', unique=True)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('raw_exif', models.JSONField(default=dict, help_text='Full EXIF tag dump before strip')),
                ('device_make', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('datetime_original', models.DateTimeField(blank=True, null=True)),
                ('datetime_digitized', models.DateTimeField(blank=True, null=True)),
                ('software', models.CharField(blank=True, max_length=200)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_altitude', models.FloatField(blank=True, null=True)),
                ('gps_speed', models.FloatField(blank=True, null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True)),
                ('stripped_at', models.DateTimeField(auto_now_add=True)),
                ('original_size_bytes', models.IntegerField(default=0)),
                ('stripped_size_bytes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Media Metadata',
                'verbose_name_plural': 'Media Metadata Records',
                'ordering': ['-stripped_at'],
            },
        ),
    ]
