# Generated by Django 6.0.5 on 2026-05-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_vault', '0002_mediagallerypage_photoreviewpage_vaulthomepage_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='')),
                ('items_per_page', models.IntegerField(default=48)),
            ],
            options={
                'verbose_name': 'Gallery Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='vaultimage',
            name='identity_tag',
            field=models.CharField(blank=True, choices=[('adalberto', 'Adalberto (Jose)'), ('monica', 'Monica'), ('little-owls', 'Little Owls School'), ('emiliano', 'Emiliano'), ('julieta', 'Julieta'), ('family', 'Family'), ('other', 'Other')], db_index=True, default='', help_text='Person this media belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultmedia',
            name='identity_tag',
            field=models.CharField(blank=True, choices=[('adalberto', 'Adalberto (Jose)'), ('monica', 'Monica'), ('little-owls', 'Little Owls School'), ('emiliano', 'Emiliano'), ('julieta', 'Julieta'), ('family', 'Family'), ('other', 'Other')], db_index=True, default='', help_text='Person this media belongs to', max_length=20),
        ),
    ]
