# Generated by Django 6.0.5 on 2026-05-15 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_history_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_incremental_at', models.DateTimeField(blank=True, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gmail Sync State',
                'verbose_name_plural': 'Gmail Sync States',
            },
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=64, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('history_id', models.CharField(blank=True, max_length=64, null=True)),
                ('subject', models.TextField(blank=True, default='')),
                ('from_address', models.CharField(blank=True, default='', max_length=500)),
                ('to_address', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('snippet', models.TextField(blank=True, default='')),
                ('labels', models.JSONField(default=list)),
                ('size_estimate', models.IntegerField(default=0)),
                ('has_attachments', models.BooleanField(default=False)),
                ('raw_path', models.TextField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('DOWNLOADED', 'Downloaded'), ('VERIFIED', 'Verified'), ('TRASHED', 'Trashed in Gmail'), ('DELETED', 'Permanently Deleted')], db_index=True, default='DISCOVERED', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('account_email', models.EmailField(db_index=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Gmail Message',
                'verbose_name_plural': 'Gmail Messages',
                'indexes': [models.Index(fields=['account_email', 'state'], name='google_gmai_account_4f228d_idx'), models.Index(fields=['account_email', 'date'], name='google_gmai_account_08a3f8_idx'), models.Index(fields=['from_address'], name='google_gmai_from_ad_3fb3ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='GmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=256)),
                ('filename', models.CharField(blank=True, default='', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size', models.IntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='google_gmail_backup.gmailmessage')),
            ],
            options={
                'verbose_name': 'Gmail Attachment',
                'unique_together': {('message', 'attachment_id')},
            },
        ),
    ]
