# Generated by Django 6.0.5 on 2026-05-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmessage',
            name='from_address',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='to_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
