# Generated by Django 6.0.5 on 2026-05-15 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0002_alter_gmailmessage_from_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('label_to_apply', models.CharField(blank=True, default='', max_length=100)),
                ('star', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Protected Sender',
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='gmailattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gmailmessage',
            options={'verbose_name': 'Gmail Message'},
        ),
        migrations.AlterModelOptions(
            name='gmailsyncstate',
            options={'verbose_name': 'Gmail Sync State'},
        ),
        migrations.CreateModel(
            name='CleanupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('gmail_query', models.TextField(help_text="Gmail search query, e.g. 'category:promotions older_than:30d'")),
                ('min_age_days', models.IntegerField(default=30, help_text='Minimum age in days before rule applies')),
                ('action', models.CharField(choices=[('trash', 'Move to Trash'), ('star', 'Star'), ('label', 'Apply Label'), ('archive', 'Archive (remove INBOX)')], max_length=20)),
                ('label_name', models.CharField(blank=True, default='', help_text='Label to apply (for action=label)', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('dry_run_default', models.BooleanField(default=True)),
                ('respect_protected_senders', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_dry', models.BooleanField(default=True)),
                ('last_affected_count', models.IntegerField(default=0)),
                ('last_dry_run_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cleanup Rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CleanupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('actor_label', models.CharField(default='system', max_length=100)),
                ('affected_count', models.IntegerField(default=0)),
                ('affected_gmail_ids', models.JSONField(default=list)),
                ('sample_subjects', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='OK', max_length=20)),
                ('error_text', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='google_gmail_backup.cleanuprule')),
            ],
            options={
                'verbose_name': 'Cleanup Audit Log',
                'ordering': ['-started_at'],
            },
        ),
    ]
