# Generated by Django 6.0.5 on 2026-05-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0003_protectedsender_alter_gmailattachment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('field', models.CharField(choices=[('sender', 'Sender (from)'), ('to', 'Recipient (to)'), ('subject', 'Subject'), ('body', 'Body'), ('label', 'Label'), ('category', 'Category'), ('has_attachment', 'Has Attachment'), ('age_days', 'Age (days)')], max_length=20)),
                ('operator', models.CharField(choices=[('contains', 'contains'), ('not_contains', 'does not contain'), ('equals', 'equals'), ('not_equals', 'does not equal'), ('starts_with', 'starts with'), ('older_than', 'older than'), ('newer_than', 'newer than'), ('is_true', 'is true')], max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('logic', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', help_text='How this condition joins with the NEXT condition', max_length=3)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='google_gmail_backup.cleanuprule')),
            ],
            options={
                'verbose_name': 'Rule Condition',
                'ordering': ['order'],
            },
        ),
    ]
