# Generated by Django 6.0.5 on 2026-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0004_rulecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupauditlog',
            name='affected_ids_truncated',
            field=models.BooleanField(default=False, help_text='True when >100 IDs were affected'),
        ),
        migrations.AlterField(
            model_name='cleanupauditlog',
            name='affected_gmail_ids',
            field=models.JSONField(default=list, help_text='First 100 IDs max'),
        ),
    ]
