# Generated by Django 6.0.5 on 2026-05-19 10:10

import google_gmail_backup.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0005_cleanupauditlog_affected_ids_truncated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanupauditlog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Cleanup Audit Log', 'verbose_name_plural': 'Cleanup Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='cleanuprule',
            options={'ordering': ['name'], 'verbose_name': 'Cleanup Rule', 'verbose_name_plural': 'Cleanup Rules'},
        ),
        migrations.AlterModelOptions(
            name='gmailattachment',
            options={'verbose_name': 'Gmail Attachment', 'verbose_name_plural': 'Gmail Attachments'},
        ),
        migrations.AlterModelOptions(
            name='gmailmessage',
            options={'verbose_name': 'Gmail Message', 'verbose_name_plural': 'Gmail Messages'},
        ),
        migrations.AlterModelOptions(
            name='gmailsyncstate',
            options={'ordering': ['email'], 'verbose_name': 'Gmail Sync State', 'verbose_name_plural': 'Gmail Sync States'},
        ),
        migrations.AlterModelOptions(
            name='protectedsender',
            options={'ordering': ['email'], 'verbose_name': 'Protected Sender', 'verbose_name_plural': 'Protected Senders'},
        ),
        migrations.AlterModelOptions(
            name='rulecondition',
            options={'ordering': ['order'], 'verbose_name': 'Rule Condition', 'verbose_name_plural': 'Rule Conditions'},
        ),
        migrations.AlterField(
            model_name='cleanupauditlog',
            name='action',
            field=models.CharField(choices=[('trash', 'Move to Trash'), ('star', 'Star'), ('label', 'Apply Label'), ('archive', 'Archive (remove INBOX)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cleanupauditlog',
            name='affected_gmail_ids',
            field=models.JSONField(default=list, help_text='First 100 affected Gmail message IDs', validators=[google_gmail_backup.models._validate_list_of_strings]),
        ),
        migrations.AlterField(
            model_name='cleanupauditlog',
            name='affected_ids_truncated',
            field=models.BooleanField(default=False, help_text='True when more than 100 messages were affected'),
        ),
        migrations.AlterField(
            model_name='cleanupauditlog',
            name='sample_subjects',
            field=models.JSONField(default=list, validators=[google_gmail_backup.models._validate_list_of_strings]),
        ),
        migrations.AlterField(
            model_name='cleanuprule',
            name='label_name',
            field=models.CharField(blank=True, default='', help_text='Label to apply (required when action=label)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cleanuprule',
            name='min_age_days',
            field=models.IntegerField(default=30, help_text='Minimum message age in days before rule applies (0 = any age)'),
        ),
        migrations.AlterField(
            model_name='gmailattachment',
            name='local_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gmailattachment',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='account_email',
            field=models.EmailField(db_index=True, help_text='Mirrors GmailSyncState.email — logical FK, not enforced at DB level.', max_length=254),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='history_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='labels',
            field=models.JSONField(default=list, validators=[google_gmail_backup.models._validate_list_of_strings]),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='raw_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gmailsyncstate',
            name='last_history_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cleanupauditlog',
            index=models.Index(fields=['-started_at'], name='google_gmai_started_36e35d_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupauditlog',
            index=models.Index(fields=['rule', '-started_at'], name='google_gmai_rule_id_319a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupauditlog',
            index=models.Index(fields=['status', '-started_at'], name='google_gmai_status_0eba19_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanuprule',
            index=models.Index(fields=['enabled', 'name'], name='google_gmai_enabled_592b81_idx'),
        ),
        migrations.AddConstraint(
            model_name='gmailmessage',
            constraint=models.CheckConstraint(condition=models.Q(('gmail_id', ''), _negated=True), name='gmail_message_id_not_empty'),
        ),
    ]
