# Generated by Django 6.0.5 on 2026-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0006_model_hardening_textchoices_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='deletion_source',
            field=models.CharField(blank=True, default='', help_text='How this message was removed: gmail_user, cleanup_rule, gmail_sync, manual', max_length=30),
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='metadata_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen copy of subject/from/to/date/labels/size at deletion time'),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='state',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('DOWNLOADED', 'Downloaded'), ('VERIFIED', 'Verified'), ('TRASHED', 'Trashed in Gmail'), ('DELETED', 'Permanently Deleted'), ('SOFT_DELETED', 'Soft Deleted (gone from Gmail, backup retained)')], db_index=True, default='DISCOVERED', max_length=20),
        ),
    ]
