# Generated by Django 6.0.5 on 2026-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0007_soft_delete_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailsyncstate',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gmailsyncstate',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
