# Generated by Django 6.0.5 on 2026-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0008_add_last_error_to_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmessage',
            name='from_email_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=320),
        ),
    ]
