# Generated by Django 6.0.5 on 2026-06-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0009_add_from_email_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailsyncstate',
            name='token_path',
            field=models.CharField(blank=True, default='', help_text='Path to per-account OAuth token. Blank = use default GOOGLE_TOKEN_FILE.', max_length=512),
        ),
    ]
