# Generated by Django 6.0.5 on 2026-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0010_add_token_path_to_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanuprule',
            name='last_dry_run_at',
            field=models.DateTimeField(blank=True, help_text='Phase 34: Execute requires a dry run newer than this timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='cleanuprule',
            name='never_delete_with_attachments',
            field=models.BooleanField(default=False, help_text='Phase 34: skip any message with an attachment, regardless of the query.'),
        ),
    ]
