# Generated by Django 6.0.5 on 2026-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0011_phase34_cleanup_safeguards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupauditlog',
            name='undone_at',
            field=models.DateTimeField(blank=True, help_text='Phase 35: set once this Trash run has been undone. Prevents double-undo.', null=True),
        ),
    ]
