# Generated by Django 6.0.5 on 2026-09-28 20:23

import django.db.models.deletion
import google_gmail_backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_gmail_backup', '0012_phase35_cleanup_undo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_domain', models.CharField(db_index=True, max_length=255)),
                ('signal_type', models.CharField(choices=[('list_unsubscribe', 'List-Unsubscribe header'), ('list_id', 'List-Id header (mailing list)'), ('precedence_bulk', 'Precedence: bulk/list'), ('reply_to_mismatch', 'From/Reply-To domain mismatch'), ('return_path_mismatch', 'From/Return-Path domain mismatch')], max_length=30)),
                ('message_count', models.IntegerField(default=0)),
                ('sample_sender', models.CharField(blank=True, default='', max_length=320)),
                ('sample_subjects', models.JSONField(default=list, validators=[google_gmail_backup.models._validate_list_of_strings])),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dismissed', models.BooleanField(default=False, help_text='Human reviewed and declined this suggestion -- do not resurface.')),
                ('created_rule', models.ForeignKey(blank=True, help_text='Set once a human accepts this suggestion and turns it into a real rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='google_gmail_backup.cleanuprule')),
            ],
            options={
                'verbose_name': 'Suggested Rule',
                'verbose_name_plural': 'Suggested Rules',
                'ordering': ['-message_count'],
                'constraints': [models.UniqueConstraint(fields=('sender_domain', 'signal_type'), name='unique_suggestion_per_domain_signal')],
            },
        ),
    ]
