# Generated by Django 5.2.7 on 2025-10-24 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to='imported/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='RUNNING', max_length=32)),
                ('totals', models.JSONField(default=dict)),
                ('error_log', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DriveAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('md5_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_path', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('DISCOVERED', 'DISCOVERED'), ('DOWNLOADED', 'DOWNLOADED'), ('IMPORTED', 'IMPORTED'), ('VERIFIED', 'VERIFIED'), ('DELETE_PENDING', 'DELETE_PENDING'), ('DELETED', 'DELETED')], default='DISCOVERED', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_media_backup.mediaitem')),
            ],
        ),
    ]
