# Generated by Django 6.0.5 on 2026-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_media_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveasset',
            name='state',
            field=models.CharField(choices=[('DISCOVERED', 'DISCOVERED'), ('DOWNLOADED', 'DOWNLOADED'), ('IMPORTED', 'IMPORTED'), ('VERIFIED', 'VERIFIED'), ('DELETE_PENDING', 'DELETE_PENDING'), ('DELETED', 'DELETED')], db_index=True, default='DISCOVERED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='driveasset',
            index=models.Index(fields=['state', 'discovered_at'], name='drive_state_discovered_idx'),
        ),
    ]
