# Generated by Django 6.0.5 on 2026-05-19 10:10

import django.db.models.deletion
import google_media_backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_media_backup', '0002_alter_driveasset_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveasset',
            options={'verbose_name': 'Drive Asset', 'verbose_name_plural': 'Drive Assets'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Item', 'verbose_name_plural': 'Media Items'},
        ),
        migrations.AlterModelOptions(
            name='runlog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Run Log', 'verbose_name_plural': 'Run Logs'},
        ),
        migrations.AlterField(
            model_name='driveasset',
            name='download_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='driveasset',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='driveasset',
            name='md5_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='driveasset',
            name='media_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_assets', to='google_media_backup.mediaitem'),
        ),
        migrations.AlterField(
            model_name='driveasset',
            name='state',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('DOWNLOADED', 'Downloaded'), ('IMPORTED', 'Imported to Vault'), ('VERIFIED', 'Verified'), ('DELETE_PENDING', 'Pending Deletion'), ('DELETED', 'Permanently Deleted')], db_index=True, default='DISCOVERED', max_length=16),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='error_log',
            field=models.JSONField(default=list, validators=[google_media_backup.models._validate_list]),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='totals',
            field=models.JSONField(default=dict, validators=[google_media_backup.models._validate_dict]),
        ),
        migrations.AddIndex(
            model_name='driveasset',
            index=models.Index(fields=['state', 'downloaded_at'], name='drive_state_downloaded_idx'),
        ),
        migrations.AddIndex(
            model_name='driveasset',
            index=models.Index(fields=['state', 'imported_at'], name='drive_state_imported_idx'),
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['-started_at'], name='google_medi_started_4bfe10_idx'),
        ),
        migrations.AddConstraint(
            model_name='driveasset',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['DISCOVERED', 'DOWNLOADED', 'IMPORTED', 'VERIFIED', 'DELETE_PENDING', 'DELETED'])), name='driveasset_valid_state'),
        ),
    ]
