# Generated by Django 6.0.5 on 2026-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('step', models.CharField(choices=[('welcome', 'Welcome'), ('admin', 'Create admin account'), ('services', 'Choose services'), ('connect', 'Connect Google'), ('storage', 'Storage location'), ('schedule', 'Schedule'), ('test', 'Test backup'), ('done', 'Done')], default='welcome', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup State',
                'verbose_name_plural': 'Setup State',
            },
        ),
    ]
