# Generated by Django 6.0.5 on 2026-09-27 08:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sampled', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('missing', models.IntegerField(default=0)),
                ('mismatched', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=list, validators=[core.models._validate_list])),
            ],
            options={
                'verbose_name': 'Integrity Run',
                'verbose_name_plural': 'Integrity Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
